name: Nginx
protocol: https
server_port: 443
topics:
  server_auth:
    links:
      - text: Configuring HTTPS servers
        url: https://nginx.org/en/docs/http/configuring_https_servers.html
      - text: Module ngx_http_ssl_module
        url: https://nginx.org/en/docs/http/ngx_http_ssl_module.html
  client_auth:
    links:
      - text: Module ngx_http_ssl_module
        url: https://nginx.org/en/docs/http/ngx_http_ssl_module.html
