name: Nginx
topics:
  server_auth:
    links:
      - https://nginx.org/en/docs/http/configuring_https_servers.html
      - https://nginx.org/en/docs/http/ngx_http_ssl_module.html
  client_auth:
    links:
      - https://nginx.org/en/docs/http/ngx_http_ssl_module.html
  client:
    links:
      - https://nginx.org/en/docs/http/ngx_http_proxy_module.html
